### ISSUE TITLE
Installing adaptiveGPCA

### ISSUE THREAD

**Issue by PratheepaJ** [jfukuyama/adaptiveGPCA#1]
When I installed adaptiveGPCA, the dependent package Iso was not installed and makes an error.
* installing *source* package ‘adaptiveGPCA’ ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘Iso’
ERROR: lazy loading failed for package ‘adaptiveGPCA’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/adaptiveGPCA’
Error: Command failed (1)

Then I installed Iso and adaptiveGPCA was installed.
install.packages("Iso")
* installing *source* package ‘adaptiveGPCA’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (adaptiveGPCA)

Would it be possible to add Iso as a dependent package? 

Thanks,
Pratheepa

**Comment by jfukuyama** [comment]
Thanks for noticing this Pratheepa, the Iso package was for an experiment I did that I ended up not using. I'll fix that today.
